import pandas as pd
import os

# Find the JSON file generated by Task 1
data_folder = "data"

json_files = [
    file for file in os.listdir(data_folder)
    if file.startswith("trends_") and file.endswith(".json")
]

json_file = os.path.join(data_folder, json_files[0])

# Load the JSON data into a Pandas DataFrame
df = pd.read_json(json_file)

print(f"Loaded {len(df)} stories from {json_file}")

# Remove duplicate stories based on the unique post_id
df = df.drop_duplicates(subset="post_id")

print(f"After removing duplicates: {len(df)}")

# Remove rows where post_id, title, or score is missing
df = df.dropna(subset=["post_id", "title", "score"])

print(f"After removing nulls: {len(df)}")

# Make sure score and num_comments are integers
df["score"] = pd.to_numeric(df["score"], errors="coerce")
df["num_comments"] = pd.to_numeric(df["num_comments"], errors="coerce")

df = df.dropna(subset=["score", "num_comments"])

df["score"] = df["score"].astype(int)
df["num_comments"] = df["num_comments"].astype(int)

# Remove stories with a score below 5
df = df[df["score"] >= 5]

print(f"After removing low scores: {len(df)}")

# Remove extra spaces from the beginning and end of titles
df["title"] = df["title"].str.strip()

# Save the cleaned data as a CSV file
output_file = "data/trends_clean.csv"

df.to_csv(output_file, index=False)

print(f"\nSaved {len(df)} rows to {output_file}")

# Print the number of stories in each category
print("\nStories per category:")
print(df["category"].value_counts())